### PR TITLE
updated API Odata API version due to upcoming deprecation

### PR DESCRIPTION
**Pull request by ebibergall**

### CODE REVIEW

**Comment by alexteusz** [comment]
@ebibergall is this ready for release?

**Comment by ebibergall** [comment]
Hey,

Yes it is. I will try to prepare it in the next few days.

Von: Alex Teusz ***@***.***>
Gesendet: Montag, 20. Februar 2023 12:36
An: Cognigy/Extensions ***@***.***>
Cc: Edi Bibergall ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL] Re: [Cognigy/Extensions] updated API Odata API version due to upcoming deprecation (PR #349)


@ebibergall<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Febibergall&data=05%7C01%7Ck.bibergall%40cognigy.com%7Cf872d89c11d54dfa074508db1336999f%7C4a7853bd0ffb40ff904cb20996f4be78%7C1%7C0%7C638124897477143912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RpI1CMb5LRlww367wCYuNLCKimAs8tqa5QoqgiHfTqM%3D&reserved=0> is this ready for release?

-

**Comment by ebibergall** [comment]
Oh I thought you had already merged this. As soon as you have I will add it to the releases page.

**Comment by ebibergall** [comment]
Had this ever been merged?

**Review by alexteusz — APPROVED** [review]

**Pull request merged**
